services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - LOW_CONFIDENCE_THRESHOLD=0.2
    volumes:
      - ./backend/model:/app/model

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: "http://backend:8000"
    ports:
      - "3000:3000"
    depends_on:
      - backend
